### ISSUE TITLE
DiscoveryClient crashes

### ISSUE THREAD

**Issue by flipback** [ASNeG/OpcUaStack#322]
**Describe the bug**

DiscoveryClient crashes by the connection to an OPC UA server.

**To Reproduce**
1. Generate an OPC UA application with OpcUaProjectBuilder3
2. Point the URL of the existent and running OPC UA server in section `<DiscoveryServer>`of **OpcUaServer.xml** file.
3. Run the application with OpcUaServer3
4. The application crushes with messages:

```
OpcUaServer3: /home/flipback/projects/ASNeG/OpcUaStack3/src/OpcUaStackCore/SecureChannel/SecureChannelBase.cpp:520: void OpcUaStackCore::SecureChannelBase::asyncWriteOpenSecureChannelRequest(OpcUaStackCore::SecureChannel *, OpcUaStackCore::OpenSecureChannelRequest &): Assertion `applicationCertificate().get() != nullptr' failed.
```

**Expected behavior**

The application must run without problems

**Environment (please complete the following information):**
 - OS: Ubuntu 19.10
 - Version 3.8.0

**Additional context**

This bug is the reason of #310.

**Comment by flipback** [comment]
Hi @huebl , I need a clew how to fix it.

**Comment by huebl** [comment]
Stack Trace:

```
#0  0x00007ffff5101428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff510302a in __GI_abort () at abort.c:89
#2  0x00007ffff50f9bd7 in __assert_fail_base (fmt=<optimized out>, 
    assertion=assertion@entry=0x7ffff64cf290 "applicationCertificate().get() != nullptr", 
    file=file@entry=0x7ffff64cf238 "/home/huebl/devel/OpcUaStack4/src/OpcUaStackCore/SecureChannel/SecureChannelBase.cpp", 
    line=line@entry=520, 
    function=function@entry=0x7ffff64cfaa0 <OpcUaStackCore::SecureChannelBase::asyncWriteOpenSecureChannelRequest(OpcUaStackCore::SecureChannel*, OpcUaStackCore::OpenSecureChannelRequest&)::__PRETTY_FUNCTION__> "void OpcUaStackCore::SecureChannelBase::asyncWriteOpenSecureChannelRequest(OpcUaStackCore::SecureChannel*, OpcUaStackCore::OpenSecureChannelRequest&)") at assert.c:92
#3  0x00007ffff50f9c82 in __GI___assert_fail (assertion=0x7ffff64cf290 "applicationCertificate().get() != nullptr", 
    file=0x7ffff64cf238 "/home/huebl/devel/OpcUaStack4/src/OpcUaStackCore/SecureChannel/SecureChannelBase.cpp", line=520, 
    function=0x7ffff64cfaa0 <OpcUaStackCore::SecureChannelBase::asyncWriteOpenSecureChannelRequest(OpcUaStackCore::SecureChannel*, OpcUaStackCore::OpenSecureChannelRequest&)::__PRETTY_FUNCTION__> "void OpcUaStackCore::SecureChannelBase::asyncWriteOpenSecureChannelRequest(OpcUaStackCore::SecureChannel*, OpcUaStackCore::OpenSecureChannelRequest&)") at assert.c:101
#4  0x00007ffff641937b in OpcUaStackCore::SecureChannelBase::asyncWriteOpenSecureChannelRequest (this=0x12bee20, secureChannel=
    0x7fffe8000b00, openSecureChannelRequest=...)
    at /home/huebl/devel/OpcUaStack4/src/OpcUaStackCore/SecureChannel/SecureChannelBase.cpp:520
#5  0x00007ffff64464ed in OpcUaStackCore::SecureChannelClient::handleRecvAcknowledge (this=0x12bee20, secureChannel=0x7fffe8000b00, 
    acknowledge=...) at /home/huebl/devel/OpcUaStack4/src/OpcUaStackCore/SecureChannel/SecureChannelClient.cpp:228
#6  0x00007ffff641784a in OpcUaStackCore::SecureChannelBase::handleReadAcknowledge (this=0x12bee20, error=..., bytes_transfered=20, 
    secureChannel=0x7fffe8000b00) at /home/huebl/devel/OpcUaStack4/src/OpcUaStackCore/SecureChannel/SecureChannelBase.cpp:335
#7  0x00007ffff6427c1d in boost::_mfi::mf3<void, OpcUaStackCore::SecureChannelBase, boost::system::error_code const&, unsigned long, OpcUaStackCore::SecureChannel*>::operator() (this=0x7ffff0b7ab28, p=0x12bee20, a1=..., a2=20, a3=0x7fffe8000b00)
    at /usr/include/boost/bind/mem_fn_template.hpp:393

```

**Comment by huebl** [comment]
The opc ua discovery client wants to open a secure channel. For this the opc ua discovery client needs a certificate. This certificate does not exist.
